version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: armandmaree/codehaven-ui:latest
    ports:
      - "8080"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: armandmaree/codehaven-ui:latest
    ports:
      - "8080"
